import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import { AppContextProvider } from "@/context/context";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import SmoothScrolling from "@/components/custom/smooth-scroll";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-main overflow-y-hidden`}>
        <SmoothScrolling>
          <AppContextProvider>
            <Header />
            {children}
            <Footer />
          </AppContextProvider>
        </SmoothScrolling>
      </body>
    </html>
  );
}
